import './styles/settings/modern-normalize.css'
import './styles/settings/global.css'
import './styles/settings/components.css'
import './styles/sections/hero.css'
import './styles/sections/about.css'
